Update deploy_pull.yml

diff --git a/.github/workflows/deploy_pull.yml b/.github/workflows/deploy_pull.yml
--- a/.github/workflows/deploy_pull.yml
+++ b/.github/workflows/deploy_pull.yml
@@ -1,30 +1,23 @@
-name: Build and Push Docker Image
-
+name: Deploy Pull
 on:
   workflow_dispatch:
-
 jobs:
-  build-and-push:
+  docker_pull:
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-
-
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
-
-      - name: Log in to Docker Hub
-        uses: docker/login-action@v3
+      - name: Verify secrets
+        run: |
+          if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then echo "DOCKER_USERNAME is missing"; exit 1; fi
+          if [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then echo "DOCKERHUB_TOKEN is missing"; exit 1; fi
+          if [ -z "${{ secrets.HOST_IP }}" ]; then echo "HOST_IP is missing"; exit 1; fi
+          if [ -z "${{ secrets.HOST_USER }}" ]; then echo "HOST_USER is missing"; exit 1; fi
+          if [ -z "${{ secrets.HOST_SSH_KEY }}" ]; then echo "HOST_SSH_KEY is missing"; exit 1; fi
+      - name: Pull Docker image
+        uses: appleboy/ssh-action@v1.0.3
         with:
-          username: ${{ secrets.DOCKER_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
-
-      - name: Build and push Docker image
-        uses: docker/build-push-action@v6
-        with:
-          context: .
-          push: true
-          tags: tomsh666/neuro_parse:latest
-          cache-from: type=gha
-          cache-to: type=gha,mode=max
+          host: ${{ secrets.HOST_IP }}
+          username: ${{ secrets.HOST_USER }}
+          key: ${{ secrets.HOST_SSH_KEY }}
+          script: |
+            echo "${{ secrets.DOCKERHUB_TOKEN }}" | sudo docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
+            sudo docker pull tomsh666/neuro_parse:latest
